package com.lazi.yelda;


public enum TERRAIN {
	MAIN_GRASS,
	MAIN_WATER,
	WATERFOUNTAIN_1,
	WATERFOUNTAIN_2,
	WATERFOUNTAIN_3,
	WATERFOUNTAIN_4,
	WATERFOUNTAIN_5,
	WATERFOUNTAIN_6,
	WATERFOUNTAIN_7,
	WATERFOUNTAIN_8,
	WATERFOUNTAIN_9,
	WATERFOUNTAIN_7_1,
	WATERFOUNTAIN_8_1,
	WATERFOUNTAIN_9_1
	;
}
